spring:
  application:
    name: neo4j-demo
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
  data:
    neo4j:
      database: student

logging:
  level:
    org:
      neo4j:
        driver: DEBUG
